import "./globals.css"

import { loadDevMessages, loadErrorMessages } from "@apollo/client/dev"
import { Inter } from "next/font/google"

import { ApolloWrapper } from "@/app/apolloWrapper"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ApolloWrapper>
      <html className="h-full antialiased" lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ApolloWrapper>
  )
}

loadDevMessages()
loadErrorMessages()
